#!/usr/bin/env python3
"""Generate the public reference-acquisition manifest (grc_library TODO 1.19.7).

The manifest [`docs/reference-acquisition-manifest.md`] is a PUBLIC BIBLIOGRAPHY of the
corpus's citation-source reference base: for each trusted-bucket entry in
`grc_library_ref/catalogue.yml` (standards / frameworks / legislation / programs) it lists
the title, version/edition, bucket, upstream URL, and acquisition class (free|licensed),
with the held source TEXT stripped. An adopter's `/adopt` uses it to bootstrap a `.ref`:
FREE sources are web-fetched, LICENSED sources are listed for manual acquisition.

**Copyright guardrail:** this reads ONLY catalogue bibliographic metadata (`title`,
`origin`/`body`/`jurisdiction`, `checked_edition`, `upstream_url`, `bucket`, `acquisition`);
it NEVER reads the held `--full-text` files nor the catalogue `notes`/`extract` fields, and
never reproduces source prose. The manifest is a bibliography, never the texts.

**Sibling-independence:** this is an ORCHESTRATOR/maintainer tool. It locates the real
`grc_library_ref` sibling via `lint_common.resolve_sibling("ref")` and NO-OPS (exit 0) when
that sibling is absent (an adopter's portable clone), so it is NEVER a CI gate and
`check-portability.sh` stays green. The maintainer-side `_ref`-required loud gate lives at
`/resume` (detect-env `ref_availability`), not here. The committed manifest ships statically,
so an adopter gets it without any sibling.

Usage:
  python3 tools/build-reference-manifest.py            # regenerate the committed manifest
  python3 tools/build-reference-manifest.py --check    # drift check (exit 1 if out of date)

`--check` is an orchestrator/maintainer drift check (it reads `_ref`), NOT a CI gate; run it
at `_ref`-update / resume, folded into the resync-`_ref` discipline.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lint_common  # noqa: E402

try:
    import yaml
except ImportError:
    print("PyYAML required", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "docs" / "reference-acquisition-manifest.md"
TRUSTED = ("standards", "frameworks", "legislation", "programs")
# Generator schema version: bump on a change to the manifest's SHAPE (columns,
# header), recorded in CHANGELOG.md. Not the library CalVer, and not the row
# contents (which advance with the reference base). The manifest is exempt from
# the date/version-staleness gates (like docs/portal.md), so this stays stable
# across content regens; the Date below is the reference base's own max currency.
SCHEMA_VERSION = "1.0.0"
FALLBACK_DATE = "2026-07-17"
BUCKET_LABEL = {
    "standards": "Standards",
    "frameworks": "Frameworks",
    "legislation": "Legislation",
    "programs": "Programs",
}


def _cell(v: str) -> str:
    """Escape a value for a markdown table cell (pipes; collapse newlines)."""
    return str(v).replace("|", "\\|").replace("\n", " ").strip()


def _issuer(bucket: str, e: dict) -> str:
    if bucket == "programs":
        return _cell(e.get("body", ""))
    if bucket == "legislation":
        return _cell(e.get("jurisdiction", ""))
    return _cell(e.get("origin", ""))


def _max_date(catalogue: dict) -> str:
    """Deterministic manifest Date: the max last_updated across trusted entries
    (the reference base's own currency), else FALLBACK_DATE. Not today() (which
    would break --check)."""
    dates = []
    for bucket in TRUSTED:
        for e in catalogue.get(bucket, []):
            for key in ("last_updated", "last_checked"):
                v = str(e.get(key, "") or "")
                if len(v) == 10 and v[4] == "-" and v[7] == "-":
                    dates.append(v)
    return max(dates) if dates else FALLBACK_DATE


def render(catalogue: dict) -> str:
    fields = [
        ("Document Title", "Reference-Acquisition Manifest"),
        ("Document Type", "Guide"),
        ("Version", SCHEMA_VERSION),
        ("Date", _max_date(catalogue)),
        ("Owner", "Governance Library Maintainer"),
        ("Approving Authority", "Governance Library Maintainer"),
        ("Related Documents", "[`README.md`](../README.md), "
         "[`docs/portal.md`](portal.md)"),
        ("Classification", "Public"),
        ("Category", "Documentation"),
        ("Review Frequency", "Regenerated from grc_library_ref/catalogue.yml on any "
         "reference-base change; maintainer-side, not a CI gate"),
        ("Repository Path", "[`docs/reference-acquisition-manifest.md`]"
         "(reference-acquisition-manifest.md)"),
        ("Confidentiality", "Public"),
        ("License", "CC BY-SA 4.0"),
    ]
    lines = [
        "<!--",
        "Auto-generated by tools/build-reference-manifest.py from "
        "grc_library_ref/catalogue.yml.",
        "Do not edit by hand. Regenerate with "
        "`python3 tools/build-reference-manifest.py`.",
        "-->",
        "",
        "# Reference-acquisition manifest",
        "",
    ]
    for i, (name, value) in enumerate(fields):
        suffix = "\\" if i < len(fields) - 1 else ""
        lines.append(f"**{name}:** {value}{suffix}")
    lines += [
        "",
        "---",
        "",
        "## Overview",
        "",
        "**Purpose.** A public bibliography of the citation-source reference base the GRC",
        "Library corpus draws on: the trusted, citation-grade sources (standards, frameworks,",
        "legislation, programs) the corpus cites as ground truth. It lists bibliographic",
        "metadata only, title, version, issuer, upstream URL, and acquisition class, so a fork",
        "adopting the library can acquire the sources it needs. It carries NO source text.",
        "",
        "**How `/adopt` uses it.** When a fork runs `/adopt`, the FREE-class sources are",
        "web-fetched into the adopter's reference sibling; the LICENSED-class sources are listed",
        "for manual acquisition (the adopter obtains them under their own licence). `/adopt`",
        "never redistributes licensed content.",
        "",
        "**Trust and scope.** Only the four citation-grade trusted buckets are listed; untrusted",
        "publications, recommendation-tier books, and scaffolding templates are excluded. The",
        "acquisition class is the source of truth held in `grc_library_ref`'s catalogue: FREE =",
        "freely and legally downloadable from the issuer; LICENSED = purchase, membership, or",
        "paywall required. A blank upstream URL means the catalogue does not yet record one.",
        "",
        "**Generated file, do not hand-edit.** Produced by `tools/build-reference-manifest.py`",
        "from `grc_library_ref/catalogue.yml`; regenerate on any reference-base change (the",
        "generator is maintainer-side, never a CI gate, so the public repo stays clonable",
        "without the private reference sibling).",
        "",
    ]
    total = 0
    free_total = 0
    for bucket in TRUSTED:
        entries = sorted(catalogue.get(bucket, []), key=lambda e: e["title"].lower())
        if not entries:
            continue
        free = sum(1 for e in entries if e.get("acquisition") == "free")
        lines += [
            f"## {BUCKET_LABEL[bucket]} ({len(entries)}: {free} free, {len(entries) - free} licensed)",
            "",
            "| Title | Version / edition | Issuer | Upstream URL | Acquisition |",
            "| --- | --- | --- | --- | --- |",
        ]
        for e in entries:
            title = _cell(e["title"])
            version = _cell(e.get("checked_edition", "") or "")
            issuer = _issuer(bucket, e)
            url = _cell(e.get("upstream_url", "") or "")
            acq = _cell(e.get("acquisition", "")).upper()
            lines.append(f"| {title} | {version} | {issuer} | {url} | {acq} |")
            total += 1
            if e.get("acquisition") == "free":
                free_total += 1
        lines.append("")
    lines += [
        f"**Total: {total} sources ({free_total} free, {total - free_total} licensed).**",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    ref = lint_common.resolve_sibling("ref")
    if ref is None:
        # Adopter / portable clone: no reference sibling. No-op (exit 0); the committed
        # manifest is used as-is. (Maintainer-side absence is caught loud at /resume.)
        note = ("build-reference-manifest: grc_library_ref not present; "
                "no-op (the committed manifest ships statically for adopters).")
        print(note)
        return 0
    catalogue_path = ref / "catalogue.yml"
    if not catalogue_path.is_file():
        print(f"build-reference-manifest: {catalogue_path} not found", file=sys.stderr)
        return 2
    catalogue = yaml.safe_load(catalogue_path.read_text(encoding="utf-8"))
    rendered = render(catalogue)
    if check:
        current = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else ""
        if current != rendered:
            print("build-reference-manifest --check: DRIFT, the committed manifest is out of "
                  "date with grc_library_ref's catalogue. Run "
                  "`python3 tools/build-reference-manifest.py` and commit.", file=sys.stderr)
            return 1
        print("build-reference-manifest --check: OK (manifest in sync with the reference base).")
        return 0
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(rendered, encoding="utf-8")
    print(f"build-reference-manifest: wrote {MANIFEST} ({rendered.count(chr(10))} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
