#!/usr/bin/env python3
"""Generate the adopter portal page and the maturity scorecard from taxonomy.yml.

Outputs two derived files under docs/:

- docs/portal.md: navigation page keyed by audience role (CIO, CISO, GRC,
  Security Architecture, Privacy, Compliance, Audit, Resilience,
  Engineering). For each role, lists the most relevant documents drawn
  from the taxonomy.
- docs/maturity-scorecard.md: per-document maturity classification
  (Mature, Baseline, Draft) derived from each document's semver. The
  classification heuristic is documented in the file.

Both files include a top-of-file 'do not edit' notice. They are
regenerated by running this script and validated by --check.

Usage:
    python3 tools/build-portal.py
    python3 tools/build-portal.py --check    # exit non-zero on drift
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TAXONOMY = REPO_ROOT / "taxonomy.yml"
PORTAL = REPO_ROOT / "docs" / "portal.md"
SCORECARD = REPO_ROOT / "docs" / "maturity-scorecard.md"

# Metadata schema version for the generator's emitted 13-field block.
# This is a deterministic constant (not derived from the per-document
# Version) because every regeneration of these derived files would
# otherwise reset their Version to the library's current value and
# force the generator-output drift gates (33 and 34) to flap on every
# PR that bumps the library version. Bump this constant manually when
# the metadata schema itself changes (e.g. a new required field, a
# rewritten Overview, an audience added or removed) and capture the
# bump in CHANGELOG.md.
PORTAL_METADATA_VERSION = "1.3.0"
SCORECARD_METADATA_VERSION = "1.0.0"

# Fallback Date if the parsed taxonomy yields no usable date values
# (defensive; production runs always have dates).
FALLBACK_DATE = "2026-06-19"

# Audience to (domain | type | path prefix | title regex) selectors.
# A document is included in an audience section if it matches at least one selector.
AUDIENCES: list[tuple[str, str, list[dict]]] = [
    (
        "CIO",
        "The Chief Information Officer needs the enterprise picture: governance, risk, technology strategy, and operational accountability.",
        [
            {"domain": "governance", "type": ("Charter", "Framework", "Policy")},
            {"domain": "risk", "type": ("Policy", "Standard")},
            {"domain": "operations", "type": ("Framework", "Standard")},
            {"path_prefix": "specification-"},
        ],
    ),
    (
        "CISO",
        "The Chief Information Security Officer needs policies, standards, and procedures that govern security architecture, identity, data protection, monitoring, and incident response.",
        [
            {"domain": "security", "type": ("Policy", "Standard", "Procedure", "Framework", "SOP", "Roadmap")},
            {"domain": "operations", "type": ("Standard", "Procedure")},
            {"domain": "dev-security", "type": ("Policy", "Standard")},
        ],
    ),
    (
        "GRC programme",
        "The GRC programme leadership needs the controlled vocabulary, registers, matrices, and the assurance cadence that the library establishes.",
        [
            {"domain": "governance"},
            {"domain": "risk", "type": ("Standard", "Procedure", "Guideline", "Register", "Template", "Annex")},
            {"domain": "compliance"},
        ],
    ),
    (
        "Security architecture",
        "Security architects need the dev-security standards, the AI security guides, the cryptographic frameworks, and the reverse framework crosswalk.",
        [
            {"domain": "dev-security"},
            {"domain": "ai", "type": ("Standard", "Framework", "Guide", "Guideline", "Procedure")},
            {"path_prefix": "security/framework-"},
            {"path_prefix": "security/standard-"},
            {"title_regex": r"Reverse Framework"},
            {"title_regex": r"Cross-Framework Alignment"},
        ],
    ),
    (
        "Privacy",
        "The Data Protection Officer needs the privacy programme charter, policy, procedures, jurisdiction annexes, and the cross-border transfer register.",
        [
            {"domain": "privacy"},
        ],
    ),
    (
        "Compliance",
        "The Chief Compliance Officer needs the compliance and audit policies, the regulatory applicability register, sector annexes, trade-compliance registers, and the audit programme.",
        [
            {"domain": "compliance"},
        ],
    ),
    (
        "Audit",
        "Internal Audit and external auditors need the internal audit standard, the control testing procedure, the audit programme, the assurance metrics, and the reverse crosswalk.",
        [
            {"path_regex": r"compliance/(standard-internal-audit|procedure-audit-planning|procedure-control-testing|procedure-capa)"},
            {"title_regex": r"Reverse Framework"},
            {"title_regex": r"Assurance Metrics"},
            {"title_regex": r"Document Index"},
            {"title_regex": r"Continuous Assurance"},
        ],
    ),
    (
        "Resilience",
        "The Resilience Owner needs the business continuity framework and policy, the disaster recovery plan, the crisis communication plan, the cross-domain coordination procedure, and the resilience metrics register.",
        [
            {"domain": "resilience"},
        ],
    ),
    (
        "Engineering",
        "Engineering leaders need the developer security standards, the DevOps and software composition standards, the secure development policy, and the AI coding assistant guidance.",
        [
            {"domain": "dev-security", "type": ("Policy", "Standard", "Guideline", "Register")},
            {"title_regex": r"AI.*Security.*Implementation"},
            {"title_regex": r"AI.*Adversarial"},
        ],
    ),
]


def parse_taxonomy() -> list[dict]:
    if not TAXONOMY.exists():
        raise SystemExit(f"FAIL: {TAXONOMY} does not exist. Run tools/build-taxonomy.py first.")
    text = TAXONOMY.read_text(encoding="utf-8")
    docs: list[dict] = []
    current: dict | None = None
    in_related = False
    related: list[str] = []
    for raw in text.splitlines():
        if raw.startswith("- path:"):
            if current is not None:
                if in_related:
                    current["related_documents"] = related
                docs.append(current)
            current = {}
            in_related = False
            related = []
            current["path"] = _yaml_value(raw, "path")
        elif raw.startswith("  ") and current is not None:
            stripped = raw.strip()
            if stripped == "related_documents: []":
                current["related_documents"] = []
            elif stripped == "related_documents:":
                in_related = True
                related = []
            elif raw.startswith("    -") and in_related:
                related.append(_yaml_list_value(raw))
            elif ": " in stripped and not stripped.startswith("-"):
                key, _, _value = stripped.partition(":")
                current[key.strip()] = _yaml_value(raw, key.strip())
                if key.strip() != "related_documents":
                    in_related = False
    if current is not None:
        if in_related:
            current["related_documents"] = related
        docs.append(current)
    return docs


def _yaml_value(line: str, key: str) -> str:
    m = re.search(rf'{re.escape(key)}:\s*"((?:[^"\\]|\\.)*)"', line)
    if not m:
        return ""
    return m.group(1).replace('\\"', '"').replace("\\\\", "\\")


def _yaml_list_value(line: str) -> str:
    m = re.search(r'-\s+"((?:[^"\\]|\\.)*)"', line)
    if not m:
        return ""
    return m.group(1).replace('\\"', '"').replace("\\\\", "\\")


def matches(doc: dict, selector: dict) -> bool:
    if "domain" in selector:
        if doc.get("domain") != selector["domain"]:
            return False
        if "type" in selector and doc.get("type") not in selector["type"]:
            return False
        return True
    if "type" in selector and doc.get("type") not in selector["type"]:
        return False
    if "path_prefix" in selector:
        if not doc.get("path", "").startswith(selector["path_prefix"]):
            return False
    if "path_regex" in selector:
        if not re.search(selector["path_regex"], doc.get("path", "")):
            return False
    if "title_regex" in selector:
        if not re.search(selector["title_regex"], doc.get("title", "")):
            return False
    return True


def select_for_audience(docs: list[dict], selectors: list[dict]) -> list[dict]:
    selected: dict[str, dict] = {}
    for d in docs:
        for sel in selectors:
            if matches(d, sel):
                selected[d["path"]] = d
                break
    return sorted(selected.values(), key=lambda x: (x.get("type", ""), x.get("title", "")))


def classify_maturity(doc: dict) -> str:
    """Classify a document by maturity based on its semver.

    Heuristic:
    - 1.x.y where x >= 1: Mature (post-baseline with structural revisions).
    - 1.0.x: Baseline (formally approved and stable).
    - 0.x.y: Draft.
    """
    version = doc.get("version", "")
    m = re.match(r"^(\d+)\.(\d+)\.(\d+)$", version)
    if not m:
        return "Unknown"
    major, minor, _patch = (int(x) for x in m.groups())
    if major >= 1 and minor >= 1:
        return "Mature"
    if major >= 1:
        return "Baseline"
    return "Draft"


def latest_source_date(docs: list[dict]) -> str:
    """Return the maximum Date across taxonomy entries, ISO-8601.

    The result is deterministic given a deterministic taxonomy.yml.
    ISO dates sort lexicographically, so ``max`` of the string values
    is correct without parsing. Falls back to ``FALLBACK_DATE`` only
    if no entry carries a date (not expected in production).
    """
    dates = [d.get("date", "") for d in docs if d.get("date", "").strip()]
    return max(dates) if dates else FALLBACK_DATE


def metadata_block(
    *,
    title: str,
    doctype: str,
    version: str,
    date: str,
    related: list[str],
    review_frequency: str,
    repo_path_link: str,
) -> list[str]:
    """Return the 13-field metadata block as a list of lines.

    Every line except the last carries the CommonMark backslash-newline
    hard-line-break marker required by ``lint-metadata.py``.
    """
    fields = [
        ("Document Title", title),
        ("Document Type", doctype),
        ("Version", version),
        ("Date", date),
        ("Owner", "Governance Library Maintainer"),
        ("Approving Authority", "Governance Library Maintainer"),
        ("Related Documents", ", ".join(related)),
        ("Classification", "Public"),
        ("Category", "Documentation"),
        ("Review Frequency", review_frequency),
        ("Repository Path", repo_path_link),
        ("Confidentiality", "Public"),
        ("License", "CC BY-SA 4.0"),
    ]
    lines: list[str] = []
    for i, (name, value) in enumerate(fields):
        suffix = "\\" if i < len(fields) - 1 else ""
        lines.append(f"**{name}:** {value}{suffix}")
    return lines


def build_portal(docs: list[dict]) -> str:
    latest_date = latest_source_date(docs)
    out: list[str] = []
    out.append("<!--")
    out.append("Auto-generated by tools/build-portal.py from taxonomy.yml.")
    out.append("Do not edit by hand. Regenerate with `python3 tools/build-portal.py`.")
    out.append("-->")
    out.append("")
    out.append("# Adopter portal")
    out.append("")
    out.extend(metadata_block(
        title="Adopter Portal",
        doctype="Guide",
        version=PORTAL_METADATA_VERSION,
        date=latest_date,
        related=[
            "[`README.md`](../README.md)",
            "[`docs/adopter-guide.md`](adopter-guide.md)",
            "[`docs/decision-tree.md`](decision-tree.md)",
            "[`docs/maturity-scorecard.md`](maturity-scorecard.md)",
            "[`governance/register-document-index-and-classification.md`](../governance/register-document-index-and-classification.md)",
        ],
        review_frequency="Regenerated from taxonomy.yml on every PR that touches source metadata; metadata schema reviewed annually",
        repo_path_link="[`docs/portal.md`](portal.md)",
    ))
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Overview")
    out.append("")
    out.append("This page is a navigation aid for the most common adopter audiences. Each section lists the documents most likely to be useful to that role, drawn from the machine-readable taxonomy and grouped by document type. The full document index lives in [`governance/register-document-index-and-classification.md`](../governance/register-document-index-and-classification.md); term definitions and acronym expansions are in the [`governance/register-glossary.md`](../governance/register-glossary.md).")
    out.append("")
    out.append("This portal is the canonical front door for adopters. The audience-keyed groupings below are the primary entry point. Five further adopter-facing documents support the portal as deeper-dive paths for specific questions; the \"Other entry points and when to use them\" section immediately below maps each to its purpose so a reader can pick the path that matches their question.")
    out.append("")
    out.append("This portal is generated; the source of truth is each document's canonical metadata block. Inclusion of a document in an audience section is selector-based; a document may legitimately appear under more than one audience.")
    out.append("")
    out.append("The metadata block above carries a generator schema constant for `Version` and the latest source `Date` found in the taxonomy. Bumps to the schema constant are recorded in [`CHANGELOG.md`](../CHANGELOG.md); the `Date` advances automatically with the corpus.")
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Other entry points and when to use them")
    out.append("")
    out.append("The portal is the canonical front door. The following adopter-facing documents are deeper-dive paths that answer specific questions. Pick by the question you are asking, not by the document name.")
    out.append("")
    out.append("| If your question is | Read | What it gives you |")
    out.append("| --- | --- | --- |")
    out.append("| \"Which documents are relevant to my role?\" | This portal (continue reading below) | Audience-keyed groupings: CIO, CISO, GRC, Security Architecture, Privacy, Compliance, Audit, Resilience, Engineering. |")
    out.append("| \"How do I fork the library, map roles, and decide what to change vs preserve?\" | [`docs/adopter-guide.md`](adopter-guide.md) | Adoption principles, the three adoption modes (fork / corpus-only / pack-only), what to change after copying, what not to change, the minimum quality bar. |")
    out.append("| \"What do I copy on Day 1?\" | [`docs/template-quickstart.md`](template-quickstart.md) | A 10-minute on-ramp: the six-artefact core baseline, role-name substitution discipline, and portal pointer. Defensible floor in one session. |")
    out.append("| \"And what do I add later?\" | [`docs/template-startup-roadmap.md`](template-startup-roadmap.md) | The long-form composition workbook: stacking modules across five dimensions (activity, data scope, audience, regulatory exposure, GRC capacity), 23 modules, three worked examples. |")
    out.append("| \"In what order should I read the documents that apply to me?\" | [`docs/decision-tree.md`](decision-tree.md) | A dimensional questionnaire (size, sector, jurisdiction, regulated activities, technology footprint) and a sequenced reading path conditional on the answers. |")
    out.append("| \"Over what calendar should I roll the programme out?\" | [`docs/template-implementation-roadmap.md`](template-implementation-roadmap.md) | Phase 1 (floor, Days 1-90), Phase 2 (operational, 91-180), and Phase 3 (Year-1 close, 181-365), pace-adjusted by GRC capacity tier. |")
    out.append("")
    out.append("The five deeper-dive paths are designed to be used together: the quickstart composes a starting set, the startup roadmap works the long-form module composition, the decision tree sequences the reading, the implementation roadmap calendars the rollout, and the adopter guide governs how the artefacts are forked and customized. Each refers to the others where the workflow crosses between them.")
    out.append("")
    out.append("For full document discovery (every artefact, machine-readable metadata, type / domain / status / related artefacts), the document index at [`governance/register-document-index-and-classification.md`](../governance/register-document-index-and-classification.md) is the comprehensive register; this portal is the audience-shaped view of the same underlying taxonomy.")
    out.append("")
    out.append("---")
    out.append("")

    for audience, blurb, selectors in AUDIENCES:
        out.append(f"## {audience}")
        out.append("")
        out.append(blurb)
        out.append("")
        selected = select_for_audience(docs, selectors)
        if not selected:
            out.append("_No documents currently match this audience._")
            out.append("")
            continue
        # Group by document type
        by_type: dict[str, list[dict]] = {}
        for d in selected:
            by_type.setdefault(d.get("type", ""), []).append(d)
        for dtype in sorted(by_type):
            out.append(f"### {dtype}")
            out.append("")
            for d in by_type[dtype]:
                path = d["path"]
                title = d.get("title", path)
                rel = f"../{path}"
                out.append(f"- [{title}]({rel})")
            out.append("")
        out.append("---")
        out.append("")
    out.append("**End of Document**")
    out.append("")
    return "\n".join(out)


def build_scorecard(docs: list[dict]) -> str:
    latest_date = latest_source_date(docs)
    out: list[str] = []
    out.append("<!--")
    out.append("Auto-generated by tools/build-portal.py from taxonomy.yml.")
    out.append("Do not edit by hand. Regenerate with `python3 tools/build-portal.py`.")
    out.append("-->")
    out.append("")
    out.append("# Document maturity scorecard")
    out.append("")
    out.extend(metadata_block(
        title="Document Maturity Scorecard",
        doctype="Register",
        version=SCORECARD_METADATA_VERSION,
        date=latest_date,
        related=[
            "[`docs/portal.md`](portal.md)",
            "[`docs/adopter-guide.md`](adopter-guide.md)",
            "[`governance/register-document-index-and-classification.md`](../governance/register-document-index-and-classification.md)",
            "[`specification-master-project.md`](../specification-master-project.md)",
        ],
        review_frequency="Regenerated from taxonomy.yml on every PR that touches source metadata; classification heuristic reviewed annually",
        repo_path_link="[`docs/maturity-scorecard.md`](maturity-scorecard.md)",
    ))
    out.append("")
    out.append("---")
    out.append("")
    out.append("## Overview")
    out.append("")
    out.append("This scorecard classifies each active artefact by maturity. The classification is derived from the document's semantic version per the heuristic below.")
    out.append("")
    out.append("| Maturity | Version range | Adopter signal |")
    out.append("| --- | --- | --- |")
    out.append("| Mature | 1.x.y where x >= 1 | The artefact has had at least one substantive revision after formal approval. Adopters should treat the artefact as stable and use it as a starting point for their own corpus. |")
    out.append("| Baseline | 1.0.x | The artefact has been formally approved and published. Adopters can use it; expect refinement on the next review cycle. |")
    out.append("| Draft | 0.x.y | The artefact is pre-formal-approval. Treat as a working draft; review carefully before adoption. |")
    out.append("")
    out.append("This classification is a heuristic derived from semver; it does not reflect audit-grade certification. See each document's metadata block for the authoritative review frequency and last review date.")
    out.append("")
    out.append("The metadata block above carries a generator schema constant for `Version` and the latest source `Date` found in the taxonomy. Bumps to the schema constant are recorded in [`CHANGELOG.md`](../CHANGELOG.md); the `Date` advances automatically with the corpus.")
    out.append("")
    out.append("---")
    out.append("")

    by_maturity: dict[str, list[dict]] = {"Mature": [], "Baseline": [], "Draft": [], "Unknown": []}
    for d in docs:
        m = classify_maturity(d)
        by_maturity[m].append(d)

    summary = ", ".join(f"{name}: {len(by_maturity[name])}" for name in ("Mature", "Baseline", "Draft", "Unknown"))
    out.append(f"_Summary as of last regeneration: {summary}._")
    out.append("")

    for maturity in ("Mature", "Baseline", "Draft", "Unknown"):
        items = by_maturity[maturity]
        if not items:
            continue
        out.append(f"## {maturity}")
        out.append("")
        out.append(f"_{len(items)} documents._")
        out.append("")
        out.append("| Path | Title | Type | Version | Date |")
        out.append("| --- | --- | --- | --- | --- |")
        for d in sorted(items, key=lambda x: x.get("path", "")):
            path = d.get("path", "")
            title = d.get("title", "")
            dtype = d.get("type", "")
            version = d.get("version", "")
            date = d.get("date", "")
            rel = f"../{path}"
            out.append(f"| [{path}]({rel}) | {title} | {dtype} | {version} | {date} |")
        out.append("")
        out.append("---")
        out.append("")
    out.append("**End of Document**")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build adopter portal and maturity scorecard.")
    parser.add_argument("--check", action="store_true",
                        help="Validate that derived files are in sync with taxonomy.yml; do not write.")
    args = parser.parse_args()

    docs = parse_taxonomy()
    portal_content = build_portal(docs)
    scorecard_content = build_scorecard(docs)

    if args.check:
        ok = True
        for path, expected in ((PORTAL, portal_content), (SCORECARD, scorecard_content)):
            if not path.exists():
                print(f"FAIL: {path.relative_to(REPO_ROOT)} does not exist.")
                ok = False
                continue
            current = path.read_text(encoding="utf-8")
            if current != expected:
                print(f"FAIL: {path.relative_to(REPO_ROOT)} is out of sync with taxonomy.")
                print("Run `python3 tools/build-portal.py` to regenerate.")
                ok = False
        if ok:
            print("OK: portal and scorecard in sync.")
            return 0
        return 1

    PORTAL.parent.mkdir(parents=True, exist_ok=True)
    PORTAL.write_text(portal_content, encoding="utf-8")
    SCORECARD.write_text(scorecard_content, encoding="utf-8")
    print(f"Wrote {PORTAL.relative_to(REPO_ROOT)} ({len(portal_content.splitlines())} lines).")
    print(f"Wrote {SCORECARD.relative_to(REPO_ROOT)} ({len(scorecard_content.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
