#!/usr/bin/env python3
"""Fail a pull request whose title or body carries Claude/Anthropic attribution (PR-time check).

Maintainer directive (2026-08-17, re-confirmed 2026-09-24): no Claude/Anthropic attribution on
any commit, push, or PR; author identity is the maintainer only. This is the AUTHORITATIVE
enforcement for PR text (maintainer ruling 2026-09-24, option A): it runs in its own workflow,
`.github/workflows/pr-attribution.yml`, on the `pull_request` event (opened, edited,
synchronize, reopened), so it re-runs whenever the title or body is edited, and it reads the PR
title and body from the event payload GitHub itself writes (`$GITHUB_EVENT_PATH`). Reading the
authoritative stored text, rather than parsing the shell command that produced it, is the point:
nine QA rounds on the PreToolUse hook showed that recognizing every shell shape that can write a
PR body is an open-ended class. The hook (`.claude/hooks/block-claude-attribution.py`) remains a
best-effort early warning; this check is the one a merge depends on.

The title and body never pass through a shell: they are read from the event JSON in Python, so
the workflow is not exposed to script injection from PR text.

GUARD-INPUT RESIDUE, stated at the point of use: this sees the PR title and body only. PR
comments and review bodies are not in the pull_request event and are not checked here; commit
messages are guarded by the local commit-msg hook. A null body is treated as empty text; an ABSENT
body key is malformed input (exit 2). The scan is quote-blind: a PR body that QUOTES an
attribution line (for example while describing this guard) fails, so such bodies paraphrase.
The generated-by pattern deliberately prefers false positives: a descriptive sentence such as
"code generated by Claude models" also fails, because the directive is absolute and a loud
failure costs one reword while a miss ships attribution.
Under `pull_request` the PR's own copy of this tool and workflow runs, so a PR that also edits
the checker could weaken it; that change is visible in the diff under the maintainer's review, and
`pull_request_target` is deliberately not used (it would not run on the PR that introduces or
changes the check, and it widens the token's reach to untrusted PR input).

Usage:
    python3 tools/check-pr-attribution.py                 # reads $GITHUB_EVENT_PATH
    python3 tools/check-pr-attribution.py --event FILE    # an explicit event JSON
    python3 tools/check-pr-attribution.py --text-file F   # scan a local PR body draft
    python3 tools/check-pr-attribution.py --self-test

Exit codes: 0 clean; 1 attribution found; 2 unreadable or malformed input (fail closed).
"""
from __future__ import annotations

import json
import os
import re
import sys

# Strict attribution shapes. Each is an attribution LINE pattern, not a model-family mention:
# "claude SHIP", "CLAUDE.md", "claude-attribution" must all pass. The PreToolUse hook carries a
# copy of this tuple; a test pins the two to identical pattern sources.
# The patterns run over THREE views of the text (the text is normalized, never the patterns widened
# per delimiter): the raw text; Markdown formatting characters replaced by spaces (so '[Claude][1]'
# and 'Claude_Code' keep their word boundaries); and the same characters deleted (so in-word
# formatting such as 'C**laud**e' or a bold '**Co-Authored-By**:' label rejoins). Newlines survive
# every view, so a match is reported as its line of the ORIGINAL text. Threat model, stated: this
# catches accidental or harness-added attribution in its ordinary Markdown shapes; deliberate
# obfuscation is a visible integrity breach in the PR text, not a parsing target.
MARKDOWN_FORMATTING = str.maketrans("*_`[]", "     ")
MARKDOWN_DELETE = str.maketrans("", "", "*_`[]")
# Emphasis and code markers deleted (they split a word), underscores and brackets spaced (they
# separate words): 'C**laud**e_Code' reads 'Claude Code'.
MARKDOWN_MIXED = str.maketrans({"*": None, "`": None, "_": " ", "[": " ", "]": " "})
# Link syntax reduced to its visible text first, so a destination or reference label never sits
# between (or glues onto) the words: '[Generated with](url) Claude' and '[CLAUDE.md][1]'.
_INLINE_LINK = re.compile(r"\]\([^)\n]*\)")
_REF_LINK = re.compile(r"\]\[[^\]\n]*\]")


def text_views(text: str) -> tuple[str, ...]:
    plain = _REF_LINK.sub("]", _INLINE_LINK.sub("]", text))
    views = [text]
    for base in (text, plain):
        views += [base.translate(MARKDOWN_FORMATTING), base.translate(MARKDOWN_DELETE),
                  base.translate(MARKDOWN_MIXED)]
    return tuple(views)

ATTRIBUTION = (
    ("a Co-Authored-By trailer naming Claude/Anthropic",
     re.compile(r"(?i)co-authored-by[ \t]*:[^\n]*\b(?:claude|anthropic)\b")),
    ("a 'Generated with/by ... Claude' attribution line",
     re.compile(r"(?i)\bgenerated\s+(?:with|by|using|via)\s+(?:(?:the\s+)?(?:help|assistance|aid)\s+of\s+)?"
                r"(?:the\s+)?(?:claude|anthropic)(?![a-z0-9]|\.md)")),
    ("a claude.ai/code link",
     re.compile(r"(?i)\bclaude\.ai/code")),
    ("a claude.com/claude-code link",
     re.compile(r"(?i)\bclaude\.com/claude-code")),
    ("the noreply@anthropic.com trailer address",
     re.compile(r"(?i)\bnoreply@anthropic\.com")),
)


class InputError(Exception):
    """The event payload or text file is missing or malformed."""


def findings(text: str) -> list[tuple[int, str, str]]:
    """(line number, label, matched text) for every attribution match. The patterns run over
    the WHOLE text (as the hook's do), so a match that spans a line break is not missed."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    raw_lines = text.split("\n")
    seen = set()
    for view in text_views(text):
        for label, rx in ATTRIBUTION:
            for m in rx.finditer(view):
                n = view.count("\n", 0, m.start()) + 1
                seen.add((n, label, raw_lines[n - 1].strip()[:120]))
    return sorted(seen)


def pr_text(event: object) -> tuple[str, str]:
    """(title, body) from a pull_request event payload; fails closed on an unexpected shape."""
    if not isinstance(event, dict) or not isinstance(event.get("pull_request"), dict):
        raise InputError("the event payload has no pull_request object")
    pr = event["pull_request"]
    if "body" not in pr:
        raise InputError("pull_request.body is absent (a null body is valid; an absent key is not)")
    title, body = pr.get("title"), pr["body"]
    if not isinstance(title, str):
        raise InputError("pull_request.title is missing or not a string")
    if body is None:
        body = ""
    if not isinstance(body, str):
        raise InputError("pull_request.body is not a string or null")
    return title, body


def check(title: str, body: str) -> list[str]:
    """Human-readable finding lines; empty when clean."""
    lines = []
    for where, text in (("title", title), ("body", body)):
        for n, label, snippet in findings(text):
            lines.append(f"PR {where} line {n}: {label}: {snippet!r}")
    return lines


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return self_test()
    try:
        if "--text-file" in argv:
            path = argv[argv.index("--text-file") + 1]
            with open(path, encoding="utf-8") as fh:
                title, body = "", fh.read()
        else:
            path = (argv[argv.index("--event") + 1] if "--event" in argv
                    else os.environ.get("GITHUB_EVENT_PATH"))
            if not path:
                raise InputError("no --event file and GITHUB_EVENT_PATH is unset")
            with open(path, encoding="utf-8") as fh:
                title, body = pr_text(json.load(fh))
    except IndexError:
        print("ERROR: --event and --text-file need a path argument", file=sys.stderr)
        return 2
    except (InputError, OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    found = check(title, body)
    if found:
        for line in found:
            print("FAIL: " + line, file=sys.stderr)
        print(
            "FAIL: the PR carries Claude/Anthropic attribution, which the maintainer directive "
            "(2026-08-17) forbids. Edit the PR title/body to remove those lines; this check "
            "re-runs on edit.",
            file=sys.stderr,
        )
        return 1
    print("OK: no Claude/Anthropic attribution in the PR title or body.")
    return 0


def self_test() -> int:
    gen = "\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)"
    coa = "Co-Authored-By: Claude Opus <noreply@anthropic.com>"
    cases = [
        ("generated line in body", ("t", "Summary.\n\n" + gen), True),
        ("co-authored trailer in body", ("t", "Body.\n\n" + coa), True),
        ("session link in body", ("t", "see https://claude.ai/code/session_abc"), True),
        ("attribution in title", ("Generated with Claude Code", ""), True),
        ("lowercase trailer", ("t", "co-authored-by: anthropic bot"), True),
        ("CRLF body", ("t", "a\r\n" + gen + "\r\n"), True),
        ("generated by", ("t", "Generated by Claude Code"), True),
        ("generated using anthropic", ("t", "generated using Anthropic tooling"), True),
        ("help-of bridge", ("t", "Generated with the help of Claude"), True),
        ("split across lines", ("t", "Generated\nwith Claude Code"), True),
        ("generated artefact prose", ("t", "docs/portal.md is generated with build-portal.py (claude SHIP)"), False),
        ("CLAUDE.md fixture", ("t", "Generated with CLAUDE.md as the input fixture"), False),
        ("bold vendor", ("t", "Generated with **Claude Code**"), True),
        ("code-span vendor", ("t", "Generated by `Claude Code`"), True),
        ("the-vendor", ("t", "Generated by the Claude app"), True),
        ("help of bold", ("t", "Generated with the help of **Claude**"), True),
        ("underscore emphasis", ("t", "Generated by _Claude_"), True),
        ("strong underscore", ("t", "Generated with __Anthropic__"), True),
        ("versioned model", ("t", "Generated by Claude-3.5-Sonnet"), True),
        ("formatted CLAUDE.md", ("t", "Generated with _CLAUDE.md_ as the fixture"), False),
        ("reference link", ("t", "Generated by [Claude][1]\n[1]: https://example.org/x"), True),
        ("snake-case product", ("t", "Generated by Claude_Code"), True),
        ("snake-case trailer", ("t", "Co-Authored-By: Claude_Bot <bot@example.org>"), True),
        ("bold trailer label", ("t", "**Co-Authored-By**: Claude Code <bot@example.org>"), True),
        ("code trailer label", ("t", "`Co-Authored-By`: Claude <bot@example.org>"), True),
        ("in-word formatting", ("t", "Generated with C**laud**e"), True),
        ("space before colon", ("t", "Co-Authored-By : Claude <bot@example.org>"), True),
        ("link around the words", ("t", "[Generated with](https://example.org/t) Claude Code"), True),
        ("reference link plus emphasis", ("t", "Generated by [C**laud**e][1]\n[1]: https://example.org/t"), True),
        ("emphasis plus underscore", ("t", "Generated with C**laud**e_Code"), True),
        ("trailer, emphasis plus underscore", ("t", "Co-Authored-By: C**laud**e_Bot <bot@example.org>"), True),
        ("reference-linked CLAUDE.md", ("t", "Generated with [CLAUDE.md][1] as the fixture."), False),
        ("clean PR", ("tooling: add a check", "Adds a check.\n\nclaude SHIP, codex SHIP."), False),
        ("CLAUDE.md mention", ("t", "Edits .claude/CLAUDE.md and the claude-attribution hook."), False),
        ("model family mention", ("t", "the Claude-family verifier returned HOLD"), False),
        ("empty body", ("t", ""), False),
    ]
    bad = []
    for name, (title, body), expect in cases:
        got = bool(check(title, body))
        if got != expect:
            bad.append(name)
        print(("PASS" if got == expect else "FAIL") + ": " + name)
    for name, event, expect in (
        ("null body accepted", {"pull_request": {"title": "t", "body": None}}, ("t", "")),
        ("absent body refused", {"pull_request": {"title": "t"}}, InputError),
        ("missing pull_request refused", {"issue": {}}, InputError),
        ("non-string title refused", {"pull_request": {"title": 5, "body": ""}}, InputError),
        ("non-string body refused", {"pull_request": {"title": "t", "body": []}}, InputError),
    ):
        try:
            got = pr_text(event)
        except InputError:
            got = InputError
        ok = got == expect
        if not ok:
            bad.append(name)
        print(("PASS" if ok else "FAIL") + ": " + name)
    total = len(cases) + 5
    print(f"self-test: {total - len(bad)}/{total} passed")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
