#!/usr/bin/env python3
"""Validate section anchors in cross-document markdown links.

Markdown links of the form `[text](path/to/file.md#anchor-name)` reference
a section heading in the target file. The existing `lint-links.py` checks
that the target file exists but does not validate that the `#anchor`
resolves to a real heading.

This linter:
- Parses all markdown links in artefact documents.
- For each link with a `#anchor`, opens the target file.
- Extracts the headings (h1-h6) and slugifies them per the GitHub flavour
  rules used by GitHub's markdown renderer.
- Fails if the anchor does not match any heading slug in the target.

The slugification rules implemented:
- Lowercase.
- Spaces → hyphens.
- Strip characters that aren't alphanumeric, hyphen, or underscore.
- Collapse consecutive hyphens to one.

Section anchors generated by GitHub for headings are deterministic
given these rules; the linter aims to match that determinism.

Same-document anchors (where the link target is just ``#anchor`` with
no file path) are resolved against the headings in the document
containing the link.

External-scheme URLs (``http://``, ``https://``, ``mailto:``, etc.) and
fenced code blocks are skipped: anchors inside example URL syntax or
inside example link syntax are documentation, not real links.

Usage:
    python3 tools/lint-section-anchors.py
    python3 tools/lint-section-anchors.py path1 path2 ...

Exit codes:
    0   no findings
    1   one or more anchor references that do not resolve
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import aiqt_bootstrap  # noqa: E402,F401  # single shim: AIQT pack tools/ on sys.path
from lint_common import REPO_ROOT, iter_markdown_targets  # noqa: E402  # grc-config/store, stays local

PACK_TOOLS = Path(__file__).resolve().parent.parent / ".corpus-management" / "tools"

DEFAULT_PATHS = [str(REPO_ROOT)]


def _engine():
    """Import the pack-owned engine, ensuring its tools/ dir is importable."""
    pack_tools = str(PACK_TOOLS)
    if pack_tools not in sys.path:
        sys.path.insert(0, pack_tools)
    import gate_lint_section_anchors  # the pack-owned engine (source of record)
    return gate_lint_section_anchors


def scan(path: Path) -> list[tuple[int, str, str, str]]:
    """Thin shim delegating to the pack engine's pure check.

    Kept in the wrapper as a module-global because the scan-scope regression
    test patches ``mod.scan`` and runs ``main``; the check (LINK_RE, HEADING_RE,
    slugify, extract_anchors, scan) lives in the pack engine. The engine takes
    ``repo_root`` as a keyword; the wrapper supplies the grc root here.
    """
    return _engine().scan(path, repo_root=REPO_ROOT)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Validate that markdown #anchor references resolve to real headings."
    )
    parser.add_argument("paths", nargs="*", default=DEFAULT_PATHS)
    args = parser.parse_args(argv[1:])
    targets = iter_markdown_targets(args.paths)
    grouped: dict[Path, list[tuple[int, str, str, str]]] = {}
    for t in targets:
        findings = scan(t)
        if findings:
            grouped[t] = findings
    if not grouped:
        print(f"OK: all #anchor references resolve to headings (scanned {len(targets)} files).")
        return 0
    total = 0
    for path, findings in sorted(grouped.items()):
        try:
            rel = path.relative_to(REPO_ROOT)
        except ValueError:
            rel = path
        print(f"=== {rel} ===")
        for lineno, target_rel, anchor, reason in findings:
            print(f"  L{lineno} [section-anchor] target {target_rel} #{anchor}: {reason}")
        total += len(findings)
    print(f"\nFAIL: {total} unresolved section anchor(s) across {len(grouped)} file(s).")
    print(
        "Markdown links of the form [text](path#anchor) must point to a real "
        "heading in the target file. Either fix the anchor to match an existing "
        "heading, update the heading, or remove the #anchor portion of the link."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
