#!/usr/bin/env python3
"""Validate section anchors in cross-document markdown links.

Markdown links of the form `[text](path/to/file.md#anchor-name)` reference
a section heading in the target file. The existing `lint-links.py` checks
that the target file exists but does not validate that the `#anchor`
resolves to a real heading.

This linter:
- Parses all markdown links in artefact documents.
- For each link with a `#anchor`, opens the target file.
- Extracts the headings (h1-h6) and slugifies them per the GitHub flavour
  rules used by GitHub's markdown renderer.
- Fails if the anchor does not match any heading slug in the target.

The slugification rules implemented:
- Lowercase.
- Spaces → hyphens.
- Strip characters that aren't alphanumeric, hyphen, or underscore.
- Collapse consecutive hyphens to one.

Section anchors generated by GitHub for headings are deterministic given
these rules; the linter aims to match that determinism.

Usage:
    python3 tools/lint-section-anchors.py
    python3 tools/lint-section-anchors.py path1 path2 ...

Exit codes:
    0   no findings
    1   one or more anchor references that do not resolve
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PATHS = [str(REPO_ROOT)]

LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)#]*)#([^)]+)\)")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")

EXEMPT_DIR_PARTS = {".git", "node_modules", "__pycache__"}


def slugify(heading: str) -> str:
    """Slugify a markdown heading per GitHub's rules (best-effort)."""
    # Remove trailing markdown formatting and code backticks
    s = heading.strip().lower()
    # Drop characters that aren't alphanumeric, space, hyphen, or underscore
    s = re.sub(r"[^a-z0-9\s\-_]+", "", s)
    # Spaces → hyphens
    s = re.sub(r"\s+", "-", s)
    # Collapse consecutive hyphens
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


def extract_anchors(text: str) -> set[str]:
    """Return set of anchor slugs derivable from headings in `text`."""
    anchors: set[str] = set()
    in_code = False
    for line in text.splitlines():
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        m = HEADING_RE.match(line)
        if m:
            heading = m.group(2)
            # Strip markdown formatting from heading text
            heading_clean = re.sub(r"[`*_]+", "", heading)
            anchors.add(slugify(heading_clean))
    return anchors


def is_target(path: Path) -> bool:
    if path.suffix != ".md":
        return False
    if any(part in EXEMPT_DIR_PARTS for part in path.parts):
        return False
    return True


def scan(path: Path) -> list[tuple[int, str, str, str]]:
    """Return list of (line, target_rel, anchor, reason) findings."""
    findings: list[tuple[int, str, str, str]] = []
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return findings
    base_dir = path.parent
    in_code = False
    for lineno, line in enumerate(text.splitlines(), start=1):
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        for m in LINK_RE.finditer(line):
            link_text, target_rel, anchor = m.group(1), m.group(2).strip(), m.group(3).strip()
            # Strip inline-code backticks from link text
            anchor = anchor.split(" ")[0]  # ignore link-title text
            if not target_rel:
                # Same-document anchor: target is the current file
                target_path = path
            else:
                # Skip external links (http/https/etc.)
                if target_rel.startswith(("http://", "https://", "mailto:")):
                    continue
                target_path = (base_dir / target_rel).resolve()
            if not target_path.exists():
                continue  # lint-links handles this
            try:
                target_text = target_path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            anchors_available = extract_anchors(target_text)
            if anchor not in anchors_available:
                try:
                    target_rel_disp = target_path.relative_to(REPO_ROOT).as_posix()
                except ValueError:
                    target_rel_disp = str(target_path)
                findings.append(
                    (lineno, target_rel_disp, anchor, f"no heading slugifies to #{anchor}")
                )
    return findings


def iter_targets(paths: list[str]) -> list[Path]:
    targets: list[Path] = []
    seen: set[Path] = set()
    for raw in paths:
        p = Path(raw).resolve()
        if p.is_file() and is_target(p):
            if p not in seen:
                targets.append(p)
                seen.add(p)
        elif p.is_dir():
            for f in p.rglob("*.md"):
                if is_target(f) and f not in seen:
                    targets.append(f)
                    seen.add(f)
    return targets


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Validate that markdown #anchor references resolve to real headings."
    )
    parser.add_argument("paths", nargs="*", default=DEFAULT_PATHS)
    args = parser.parse_args(argv[1:])
    targets = iter_targets(args.paths)
    grouped: dict[Path, list[tuple[int, str, str, str]]] = {}
    for t in targets:
        findings = scan(t)
        if findings:
            grouped[t] = findings
    if not grouped:
        print(f"OK: all #anchor references resolve to headings (scanned {len(targets)} files).")
        return 0
    total = 0
    for path, findings in sorted(grouped.items()):
        try:
            rel = path.relative_to(REPO_ROOT)
        except ValueError:
            rel = path
        print(f"=== {rel} ===")
        for lineno, target_rel, anchor, reason in findings:
            print(f"  L{lineno} [section-anchor] target {target_rel} #{anchor}: {reason}")
        total += len(findings)
    print(f"\nFAIL: {total} unresolved section anchor(s) across {len(grouped)} file(s).")
    print(
        "Markdown links of the form [text](path#anchor) must point to a real "
        "heading in the target file. Either fix the anchor to match an existing "
        "heading, update the heading, or remove the #anchor portion of the link."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
